### PR TITLE
Added image for loosers assemble.

### PR DESCRIPTION
**Pull request by k0nG**
A nice image for the page.

### CODE REVIEW

**Comment by anglepoised** [comment]
:baby_bottle:

**Comment by orangespaceman** [comment]
When I get time I will swap this for the photo I was taking when this photo was taken.

Two advantages: 
1. Less meta
2. Less bald spot

**Comment by orangespaceman** [comment]
https://www.flickr.com/photos/thegingerbloke/17724093980/

**Comment by k0nG** [comment]
That is a better shot for sure.

**Comment by anglepoised** [comment]
That really captures the spirit of the event for me (even though I wasn't there). I'd like to see the rest of those slides. There are more, right?

**Pull request merged**
