### PR TITLE
Add Boothy's text

### PR DESCRIPTION
**Pull request by jamescooke**
Text for International Men's Day.

### CODE REVIEW

**Comment by jamescooke** [comment]
@jamesbooth

**Comment by jedrichards** [comment]
@jamesbooth Thanks for your talk James, found it very interesting and relevant. Good on you for bringing it up. It's something I read and think about a lot.

I think I may think about it a little bit differently to you, though. For my part, I think the crisis in masculinity is partly to do with how we've come to think about gender in society, and partly to do with the changes happening in society.

In this country especially, in the space of a few generations we've moved from a work culture that rewards physical strength to one which rewards thinking quietly in offices. This has hit the working class male especially hard, which afaiu is where a large fraction of the suicide statistics are coming from. I'm pretty sure it's not affluent 30 something web workers like us that are killing ourselves in ever higher numbers, for example. In other words, the crisis in masculinity can at least (partly) be viewed as due to a feminisation of the work place, rather than being blamed on men's own inability to talk about their feeling like women do.

So I find the idea that in order to fix themselves men should become more like women is, at best, somewhat troubling. In many ways a male "safe space" is one where feelings may not be _directly_ talked about, instead males bond and recharge emotionally as they have done for hundreds of thousands of years; by talking about practical concerns, abstract matters, hobbies, sports and forming group hierarchies and roles. Men are comforted by having a use and by providing practical value related to their greater connectedness to the physical world. Evolutionarily this is due to a man's value only being worth as much as the practical value he brings to his tribe (an occasional squirt of semen being the least of it), whereas women provide innate value simply by being, since they have the uterus.

Equality is great, I'm 100% for it, but modern feminism has meant we've spent the last ~20 years concentrating almost exclusively on women's issues, and this at a time when traditional working class male roles and jobs are being additionally eroded. Like you say, men are taking their own lives at a greater rate than women. They also are,
- Falling being in secondary and university education
- Face a 2:1 bias against being hired for a STEM or tech job by a similarly qualified female
- Earn less than similarly qualified women while in their 20s and 30s
- Comprise 94% of all deaths at work
- Much more likely to be the victim of violence and comprise about 80% of murder victims
- Only receive child custody in about 15% of cases
- Form >98% of deaths in battle in recent wars
- Are are more likely to be homeless
- Die younger from preventable diseases
- For a similar criminal offence men receive on average 63% longer sentences as women. This is 6x larger than any discrepancy noted between white men and black men
- Face a constant barrage of criticism from the left wing media for "patriarchy", "rape culture", "oppression", "toxic masculinity"

My thinking is that the above has more effect on suicide rates than an inability to talk about our feels. In many ways I feel that is victim blaming.

So yes, I think International Men's Day is great, but personally I'll be thinking about how we can rebuild masculinity without feminising it, and celebrates the differences between men and women without dividing us.

Thanks! :+1:

**Comment by jamescooke** [comment]
Hey Jed. Thanks for sharing your experience and thoughts.

Where you've written...

> personally I'll be thinking about how we can rebuild masculinity without feminising it

... May I recommend the following book which I believe may help you with that task: "Manhood" By Steve Biddulph https://books.google.co.uk/books?id=DKFebzuV8f4C (I have a copy if you'd like to borrow it).

**Comment by jedrichards** [comment]
Thanks, yes please, that'd be great.

**Comment by jamescooke** [comment]
:+1:

**Comment by jamesbooth** [comment]
@jedrichards,

Thank you for sharing your thoughts, it's good to know the talk sparked some interest.

Since getting involved with the charity I've been on quite a personal journey of discovery, learning a great deal about myself. A lot of this I'm still kind of working out for myself, and will be working out for the rest of my life. It's something I now feel passionately about and want to try and share with all my friends.

The main problem with my HMTL talk was that it wasn't long enough. Those thoughts I shared only scratch the surface of some of the issues with our Patriarchal society. I'm not denying that men don't have problems, but compared to women, we're still out in front.
http://www.newstatesman.com/politics/2014/08/robert-webb-roll-roll-see-man-talking-about-feminism-what-could-possibly-go-wrong

Another problem with discussing this subject is that most comments are very binary. Masculine / feminine. I know I don't conform 100% to what society considers "manly', so presuming that people are either 100% one or 100% the other can be misleading. It's something I'm trying to address in the language I use.

Regarding your comment about…
'male "safe space" is one where feelings may not be directly talked about'
According to the guidance from CALM on suicide…
'Calls to Calm’s helpline (0800 58 58 58) suggest that it is a myth that men do not want to talk about their problems. “But too often they don’t feel comfortable doing so with friends, family and colleagues,”'
http://www.theguardian.com/society/2015/oct/31/social-media-campaign-male-suicide
Why do you think this is?

Having Mental health issues is something that has been linked with suicide. The charity Mind have reported that 1 in 4 people in the UK will experience a mental health problem each year. That is something that crosses all gender and wealth demographics.
http://www.mind.org.uk/information-support/types-of-mental-health-problems/statistics-and-facts-about-mental-health/how-common-are-mental-health-problems/

The Intersectional Feminism I support stands for equality in our society. As I've come to learn more about the issues women face, I can completely understand why Feminism has focused on fixing issues that affect women. Maybe the more men that get involved, the more of mens issues will also start to get looked at?

Something interesting I heard recently.
Patriarchy only serves itself.
Men do better out of it, but it still doesn't help us.

James

**Comment by jedrichards** [comment]
Cool, thanks for your response :+1: 

I think where our opinions overlap is in a general concern over these sorts of issues, and a desire to see things improve, which is great.

But I think we'll probably have to agree to disagree over the helpfulness of modern feminism (3rd wave, intersectional, identity politics etc.). I find a lot of the thinking coming from that camp as divisive, authoritarian, illiberal, anti-free speech, based on about ~20 years of shoddy and self-serving academic output from the social sciences and largely factually refutable. What's more I feel it has crossed over into dogmatic ideology that comes attached with a large social stigma for any sort of rational challenge.

I don't think the patriarchy is real, as is sold to us by modern feminism. It encourages a harmful and divisive "men vs. women" attitude, whereas in reality behind every man or woman that has concentrated on their career there is likely a family unit that they are providing for. It silences and demeans every woman or man that may value family and social experiences more than worklife. I'm not ashamed to admit that my views in this area are probably quite traditionalist and conservative, but I've been pushed in that direction observing the actions of the monster of gender and identity politics that has emerged in the last 5 years or so.

Sorry, don't mean this to be overly challenging! And I respect your views, but I'm just really not sure modern intersectional identity and gender politics is the way to fix things. I don't think we should debate this here, we're unlikely to change each other's minds, but feel like it's important to get a counter viewpoint out there!

Laters! :smile:

**Comment by jamesbooth** [comment]
@jedrichards 

I welcome the debate, I wouldn't have brought it up otherwise. Just so you know, the Feminism I'm getting behind is 4th wave. 

I would be interested in continuing this another time, face to face :smile:  

Thank you

**Comment by jedrichards** [comment]
We come at this from very different positions. Yeap, would be good to discuss sometime. Debate is healthy!

**Pull request merged**
